set(_CATKIN_CURRENT_PACKAGE "custom_msgs")
set(custom_msgs_VERSION "2.0.2")
set(custom_msgs_MAINTAINER "Tully Foote <tfoote@osrfoundation.org>")
set(custom_msgs_PACKAGE_FORMAT "1")
set(custom_msgs_BUILD_DEPENDS "geometry_msgs" "message_generation" "std_msgs" "sensor_msgs" "rospy" "roscpp" "rosjava_bootstrap" "rosjava_messages")
set(custom_msgs_BUILD_EXPORT_DEPENDS "geometry_msgs" "message_runtime" "std_msgs" "rospy" "roscpp" "sensor_msgs" "message_generation")
set(custom_msgs_BUILDTOOL_DEPENDS "catkin")
set(custom_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(custom_msgs_EXEC_DEPENDS "geometry_msgs" "message_runtime" "std_msgs" "rospy" "roscpp" "sensor_msgs" "message_generation")
set(custom_msgs_RUN_DEPENDS "geometry_msgs" "message_runtime" "std_msgs" "rospy" "roscpp" "sensor_msgs" "message_generation")
set(custom_msgs_TEST_DEPENDS )
set(custom_msgs_DOC_DEPENDS )
set(custom_msgs_DEPRECATED "")